apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: orderflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      containers:
        - name: nginx-gateway
          image: nginx:1.27
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
  namespace: orderflow
spec:
  type: ClusterIP
  selector:
    app: nginx-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
