events {}

http {
  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

  upstream product_service {
    server host.docker.internal:4001;
  }

  upstream order_service {
    server host.docker.internal:4002;
  }

  server {
    listen 8080;

    location /health {
      return 200 "api-gateway ok\n";
    }

    location /api/products/ {
      limit_req zone=api_limit burst=20 nodelay;
      limit_req_status 429;

      proxy_pass http://product_service/products/;
      proxy_set_header Host $host;
      proxy_set_header X-Request-ID $request_id;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

    }

    location /api/orders/ {
      limit_req zone=api_limit burst=20 nodelay;
      limit_req_status 429;

      proxy_pass http://order_service/orders/;
      proxy_set_header Host $host;
      proxy_set_header X-Request-ID $request_id;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      
    }

    location /uploads/ {
        proxy_pass http://product_service/uploads/;
        proxy_set_header Host $host;
        proxy_set_header X-Request-ID $request_id;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
